[tool.mypy]
# See https://mypy.readthedocs.io/en/latest/config_file.html for more mypy options.

plugins = ["mypy_django_plugin.main"]

# Enables the type-checker on the interior of functions without type annotations.
check_untyped_defs = true

# Displaying specific error codes makes it easier to silence specific errors
# See also https://mypy.readthedocs.io/en/latest/error_codes.html
show_error_codes = true

# Show source code snippets and location markers in error messages
pretty = true

# Suppresses errors about packages which do not implement type-hint sharing.
# See also https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports.
ignore_missing_imports = true


[tool.django-stubs]
django_settings_module = "django_social.settings"
